# Generated by Django 6.1 on 2026-09-01 22:24

import apps.finance.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('invoice_number', models.CharField(default=apps.finance.models.generate_invoice_number, editable=False, max_length=50, unique=True, verbose_name='invoice number')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='issue date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount due')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='currency')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('booking', models.ForeignKey(help_text='The booking this invoice relates to.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tours.booking')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('ITINERARY', 'Itinerary'), ('VOUCHER', 'Voucher'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='document type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(help_text='Stored under media/documents/YYYY/MM/. Swap upload_to for cloud storage later.', upload_to='documents/%Y/%m/', verbose_name='file')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tours.booking')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('payment_date', models.DateField(verbose_name='payment date')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount paid')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('MPESA', 'M-Pesa'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=30, verbose_name='payment method')),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference, M-Pesa transaction code, etc.', max_length=100, verbose_name='reference / transaction number')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('invoice', models.ForeignKey(help_text='The invoice this payment is for.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
