# Generated by Django 6.1 on 2026-09-11 14:41

import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('organizations', '0002_alter_organization_is_active'),
        ('tours', '0002_alter_booking_customer_alter_booking_inquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Stored under media/documents/YYYY/MM/. Cloud storage can be added later.', upload_to='documents/%Y/%m/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=apps.finance.models.generate_invoice_number, editable=False, max_length=50, verbose_name='invoice number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'invoice_number'), name='unique_invoice_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_due__gte', 0)), name='invoice_amount_due_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gt', 0)), name='payment_amount_positive'),
        ),
    ]
