# Generated by Django 6.1 on 2026-09-01 22:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='license number')),
                ('languages_spoken', models.CharField(blank=True, help_text='Comma-separated list, e.g. English, Swahili, French', max_length=255, verbose_name='languages spoken')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('organization', models.ForeignKey(help_text='The organization this guide works for.', on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='organizations.organization')),
                ('user', models.OneToOneField(blank=True, help_text='Optional: Link to a system user account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'guide',
                'verbose_name_plural': 'guides',
                'ordering': ['organization', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SafariPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='package name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='duration (days)')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per person in USD.', max_digits=10, verbose_name='base price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(help_text='The organization offering this package.', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'safari package',
                'verbose_name_plural': 'safari packages',
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('total_passengers', models.PositiveIntegerField(default=1, verbose_name='total passengers')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed price for this booking.', max_digits=12, null=True, verbose_name='total price')),
                ('special_notes', models.TextField(blank=True, verbose_name='special notes')),
                ('customer', models.ForeignKey(help_text='The customer making this booking.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='crm.customer')),
                ('inquiry', models.ForeignKey(blank=True, help_text='The originating inquiry, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='crm.inquiry')),
                ('organization', models.ForeignKey(help_text='The organization managing this booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='organizations.organization')),
                ('package', models.ForeignKey(blank=True, help_text='The predefined package, if applicable (leave blank for custom tours).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tours.safaripackage')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='registration number')),
                ('make', models.CharField(help_text='e.g. Toyota', max_length=100, verbose_name='make')),
                ('model', models.CharField(help_text='e.g. Land Cruiser', max_length=100, verbose_name='model')),
                ('capacity', models.PositiveIntegerField(default=7, verbose_name='passenger capacity')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('organization', models.ForeignKey(help_text='The organization that owns this vehicle.', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'ordering': ['organization', 'make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='TourAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notes', models.TextField(blank=True, verbose_name='operational notes')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tours.booking')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tours.guide')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tours.vehicle')),
            ],
            options={
                'verbose_name': 'tour assignment',
                'verbose_name_plural': 'tour assignments',
                'ordering': ['booking__start_date'],
            },
        ),
    ]
