# Generated by Django 6.1 on 2026-09-01 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('organization', models.ForeignKey(help_text='The organization this customer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('LOST', 'Lost')], default='NEW', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('organization', models.ForeignKey(help_text='The organization this lead belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('QUOTED', 'Quoted'), ('BOOKED', 'Booked'), ('CLOSED', 'Closed')], default='NEW', max_length=20, verbose_name='status')),
                ('destination_interest', models.CharField(blank=True, max_length=255, verbose_name='destination interest')),
                ('expected_travel_date', models.DateField(blank=True, null=True, verbose_name='expected travel date')),
                ('number_of_travelers', models.PositiveIntegerField(default=1, verbose_name='number of travelers')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='estimated budget')),
                ('special_requirements', models.TextField(blank=True, verbose_name='special requirements')),
                ('customer', models.ForeignKey(blank=True, help_text='The established client who made this inquiry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='crm.customer')),
                ('organization', models.ForeignKey(help_text='The organization handling this inquiry.', on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='organizations.organization')),
                ('lead', models.ForeignKey(blank=True, help_text='The prospective client who made this inquiry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='crm.lead')),
            ],
            options={
                'verbose_name': 'inquiry',
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
