# Generated by Django 6.1 on 2026-09-01 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='company name')),
                ('domain', models.CharField(blank=True, help_text='Optional custom domain or subdomain for the company.', max_length=100, null=True, unique=True, verbose_name='domain/subdomain')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this organization should be treated as active.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
    ]
